/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prognoz.panels;

import com.prognoz.models.Batches;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComponent;

/**
 *
 * @author Kavita
 */
public class BatchNamesPanel extends javax.swing.JPanel {

    /**
     * Creates new form BatchNamesPanel
     */
    public BatchNamesPanel() {
        initComponents();
        List<String> batchesName = Batches.getBatches();
        for (String object : batchesName) {
            JComponent component = new JButton(object);
            this.add(component);
        }
    }

    public static void main(String[] args) {
        new BatchNamesPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
